Repository bloom-housing/ui-components, pull requests merged in 2023-03, with the labels that each got.

#34 feat(stackedtable): add cell array support
  src/global/tables.scss
  src/tables/StackedTable.stories.tsx
  src/tables/StackedTable.tsx
Labels: 1 review needed

#38 fix: fix type issues
  .circleci/config.yml
  src/tables/StackedTable.tsx
Labels: ready to merge

#40 fix: Add optional background to page header
  src/headers/PageHeader.stories.tsx
  src/headers/PageHeader.tsx
Labels: ready to merge

#26 feature: align modal with detroit updates
  src/global/tokens/sizes.scss
  src/overlays/Modal.scss
  src/overlays/Modal.stories.tsx
  src/overlays/Modal.tsx
Labels: ready to merge

#41 fix: align InfoCard and InfoCardGrid with detroit updates
  src/blocks/InfoCard.scss
  src/blocks/InfoCard.stories.tsx
  src/blocks/InfoCard.tsx
  src/page_components/listing/AdditionalFees.stories.tsx
  src/sections/InfoCardGrid.scss
  src/sections/InfoCardGrid.tsx
Labels: ready to merge

#45 fix: align ViewItem with detroit updates
  src/blocks/ViewItem.scss
  src/blocks/ViewItem.tsx
Labels: ready to merge

#46 fix: align Button with detroit updates
  src/actions/Button.scss
  src/actions/Button.tsx
  src/icons/Icon.scss
  src/icons/Icon.tsx
Labels: ready to merge

#47 fix: align ExpandableContent with detroit updates
  src/actions/ExpandableContent.stories.tsx
  src/actions/ExpandableContent.tsx
Labels: ready to merge

#44 feat: align ActionBlock with detroit updates
  __tests__/blocks/ActionBlock.test.tsx
  package.json
  src/blocks/ActionBlock.scss
  src/blocks/ActionBlock.stories.tsx
  src/blocks/ActionBlock.tsx
  tailwind.config.js
  yarn.lock
Labels: ready to merge

#89 fix: add explicit dependency
  package.json
Labels: ready to merge

#49 fix: align Field with detroit updates
  src/forms/Field.tsx
Labels: ready to merge

#50 fix: align HeadingGroup with detroit updates
  src/headers/HeadingGroup.tsx
Labels: ready to merge

#51 fix: align Hero with detroit updates
  src/headers/Hero.scss
  src/headers/Hero.stories.tsx
  src/headers/Hero.tsx
Labels: ready to merge

#53 fix: align PageHeader with detroit updates
  src/headers/PageHeader.scss
  src/headers/PageHeader.stories.tsx
Labels: ready to merge

#65 fix: align StepHeader with detroit updates
  src/headers/StepHeader.scss
  src/headers/StepHeader.tsx
Labels: ready to merge

#66 fix: align FooterNav with detroit updates
  src/navigation/FooterNav.scss
Labels: ready to merge

#68 fix: align LanguageNav with Detroit updates
  src/navigation/LanguageNav.scss
  src/navigation/LanguageNav.stories.tsx
Labels: ready to merge

#70 fix: align ProgressNav with detroit updates
  src/navigation/ProgressNav.tsx
Labels: ready to merge

#71 fix: align AlertBox with detroit updates
  src/notifications/AlertBox.scss
  src/notifications/AlertBox.tsx
Labels: ready to merge

#74 fix: align Drawer with detroit updates
  src/overlays/Drawer.scss
Labels: 1 review needed, ready to merge

#90 fix: update ux issues in category table
  src/global/tables.scss
  src/global/text.scss
  src/page_components/listing/ContentAccordion.tsx
  src/tables/CategoryTable.stories.tsx
  src/tables/CategoryTable.tsx
Labels: ready to merge

#76 fix: align LoadingOverlay with detroit updates
  src/overlays/LoadingOverlay.scss
Labels: ready to merge

#78 fix: align Overlay with detroit updates
  src/overlays/Overlay.scss
Labels: ready to merge

#79 fix: align ListingCard with detroit updates
  src/page_components/listing/ListingCard.scss
  src/page_components/listing/ListingCard.stories.tsx
  src/page_components/listing/ListingCard.tsx
Labels: ready to merge

#82 fix: align GridSection with detroit updates
  src/sections/GridSection.scss
  src/sections/GridSection.stories.tsx
  src/sections/GridSection.tsx
Labels: ready to merge

#84 fix: align Description with detroit updates
  src/text/Description.scss
  src/text/Description.stories.tsx
  src/text/Description.tsx
Labels: ready to merge

#80 fix: align ListingDetailHeader with detroit updates
  src/global/app-css.scss
  src/global/headers.scss
  src/page_components/listing/ContentAccordion.scss
  src/page_components/listing/ListingDetailHeader.scss
  src/page_components/listing/ListingDetailHeader.stories.tsx
  src/page_components/listing/ListingDetailHeader.tsx
  src/page_components/listing/ListingDetails.scss
  src/page_components/listing/ListingDetails.tsx
Labels: ready to merge

#43 feat: align FormCard with detroit updates
  __tests__/blocks/FormCard.test.tsx
  src/blocks/FormCard.scss
  src/blocks/FormCard.stories.tsx
  src/blocks/FormCard.tsx
  src/global/mixins.scss
Labels: 1 review needed
